/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jakabobnar_colorprofile_WinColorProfileLoader */

#ifndef _Included_com_jakabobnar_colorprofile_WinColorProfileLoader
#define _Included_com_jakabobnar_colorprofile_WinColorProfileLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jakabobnar_colorprofile_WinColorProfileLoader
 * Method:    getColorProfilesLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jakabobnar_colorprofile_WinColorProfileLoader_getColorProfilesLocation
  (JNIEnv *, jobject);

/*
 * Class:     com_jakabobnar_colorprofile_WinColorProfileLoader
 * Method:    getColorProfiles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jakabobnar_colorprofile_WinColorProfileLoader_getColorProfiles
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
